import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import "@payroc/react/build/styles.css";
import Image from "next/image";

import Logo from "@/public/payroc-white.png";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { Avatar } from "@payroc/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="nav flex justify-between">
          <Image src={Logo} alt="Payroc Logo" />
        </nav>
        {children}
      </body>
    </html>
  );
}
